name: CI/CD pipeline for main branch

on:
  push:
    branches:
      - main

env:
  PYTHONPATH: api/src/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'eu-west-1' 

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        cd api/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install dev dependencies
      run: |
        cd api/
        pip install -r requirements-dev.txt
    - name: Test with pytest
      run: pytest
    - name: Code analysis
      run: |
        cd api/
        flake8 src

  test_cdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        version: 10.x
    - name: Install dependencies
      run: |
        cd infrastructure/
        npm install
    - name: CDK unit tests
      run: |
        cd infrastructure/
        npm test

# TODO - React unit tests
# TODO - Cypress tests

  deploy_dev_infrastructure:
    needs: [test_api, test_cdk]
    runs-on: ubuntu-latest
    steps:
      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'diff'
          working_dir: 'infrastructure'
          cdk_stack: 'dev-data-access-management'
          actions_comment: false   
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v1
        with:
          cdk_subcommand: 'deploy'
          working_dir: 'infrastructure'
          cdk_stack: 'dev-data-access-management'
          cdk_args: '--require-approval never'
          actions_comment: false

# TODO - build React app and copy files to S3 bucket for static website - dev

# TODO - deploy test infrastructure using CDK
# TODO - build React app and copy files to S3 bucket for static website - test
# TODO - e2e tests API

# TODO - deploy live infrastructure using CDK
# TODO - build React app and copy files to S3 bucket for static website - live